### ISSUE TITLE
to do: PDF embedden

### ISSUE THREAD

**Issue by EstherDeLoof** [OpenWebslides/ICT-Lerarenopleiding#8]
The pdf (see last slide) is embedded, but it doesn't always open in the most elegant way (zoom not optimal and controls not visible). Can this be solved?

**Comment by RubenVerborgh** [comment]
This seems to be a rendering bug with the built-in PDF viewer. Very strange, but not immediately fixable.

**Comment by RubenVerborgh** [comment]
(It's a bug in Chrome; Firefox does it fine.)

**Comment by EstherDeLoof** [comment]
OK, thanks for taking a look!
